# Modeling

In [4]:
import pandas as pd
import numpy as np
import os
import pickle
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import __version__ as sklearn_version
from sklearn.model_selection import train_test_split, cross_validate, GridSearchCV, learning_curve
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
from sklearn.pipeline import make_pipeline

In [5]:
# import data
wnv = pd.read_csv('../data/wnv.csv')
wnv.head().T

                     0         1         2         3         4
Latitude      1.020679  1.020679  1.020679  1.020679  1.020679
Longitude    -0.456184 -0.456184 -0.456184 -0.456184 -0.456184
NumMosquitos -0.214187 -0.214187 -0.214187 -0.214187 -0.185014
Tmax          1.207871 -0.521855  0.432476  1.207871  1.207871
Tmin          1.097651 -0.081256  0.770177  0.770177  0.770177
...                ...       ...       ...       ...       ...
Month_10      0.000000  0.000000  0.000000  0.000000  0.000000
Year_2007     1.000000  1.000000  1.000000  1.000000  1.000000
Year_2009     0.000000  0.000000  0.000000  0.000000  0.000000
Year_2011     0.000000  0.000000  0.000000  0.000000  0.000000
Year_2013     0.000000  0.000000  0.000000  0.000000  0.000000

[241 rows x 5 columns]

In [6]:
# train test split
X_train, X_test, y_train, y_test = train_test_split(wnv.drop(columns='WnvPresent'), 
                                                    wnv.WnvPresent, test_size=0.3, 
                                                    random_state=47)